apiVersion: kubedb.com/v1alpha1
kind: MySQL
metadata:
  name: mysql-quickstart
  namespace: demo
spec:
  version: "8.0"
  doNotPause: true
  storage:
    storageClassName: "standard"
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 50Mi
---
apiVersion: v1
kind: Secret
metadata:
  namespace: demo
  name: mysql-pass 
type: Opaque
data:
  password: cGFzc3dvcmQ=
---  
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-volumeclaim 
  namespace: demo
  labels:
    app: wordpress
spec:
  #storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: wordpress
  name: wordpress
spec:
  type: LoadBalancer #ClusterIP # LoadBalancer
  ports:
    - port:  80
      targetPort: 80
      protocol: TCP
  selector:
    app: wordpress
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: wordpress
  namespace: demo
  labels:
    app: wordpress
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
        - image: jjswain2018/wisdmlabs-nginx-php7.2-wordpress:v02
          name: wordpress
          env:
          - name: URL
            value: testwisdm.com
          - name: TITLE
            value: OH_MY_GOD_BLESS_WISDMLABS_PHP7.2
          - name: USER
            value: user1
          - name: EMAIL
            value: devops@gmail.com
          - name: PASSWORD
            value: password
          - name: MYSQL_DB_HOST
            value: mysql-cluster-0.mysql-cluster.default.svc.cluster.local #mysql-connect , this line not required 
          - name: WORDPRESS_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-pass 
                key:  password
          ports:
            - containerPort: 80
              name: wordpress
          readinessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 20 
          volumeMounts:
          - name: wordpress-persistent-storage
             # mountPath: /var/www/html
            mountPath: /usr/share/nginx/wwww 
      initContainers:
      - name: install
        image: jjswain2018/wisdmlabs-nginx-php7.2-wordpress:v02
        command: ["/bin/bash", "-c",
                 "cp -rf * /usr/share/nginx/html"]
        env:
          - name: MYSQL_DB_HOST
            value: mysql-cluster-0.mysql-cluster.default.svc.cluster.local  #mysql-connect , this line not required
          - name: WORDPRESS_DB_PASSWORD 
            valueFrom:
              secretKeyRef:
                name: mysql-pass 
                key:  password
        # command: ["/bin/bash", "-c",
        #          "cp -rf * /usr/share/nginx/html",
        #           "wp --allow-root core install  --url=testwp.com --title=DEVOPS-Wisdm --admin_user=anyuser --admin_password=password --admin_email=devops@gmail.com"]
        volumeMounts:
        - name: wordpress-persistent-storage
          mountPath: "/usr/share/nginx/html"
      volumes:
      - name: wordpress-persistent-storage
        persistentVolumeClaim:
            claimName: wordpress-volumeclaim